apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
type: Opaque
stringData:
  ELASTICSEARCH_HOST: http://quickstart-es-default:9200
  ELASTICSEARCH_API_KEY: <insert your APIKey>
  ELASTICSEARCH_INDEX: konnect

